# This file was generated by GoReleaser. DO NOT EDIT.
cask "scout-cli" do
  name "scout-cli"
  desc "Scout APM CLI — monitor application performance from the terminal"
  homepage "https://github.com/scoutapp/scout-cli"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scout"

  on_macos do
    on_intel do
      url "https://github.com/scoutapp/scout-cli/releases/download/v#{version}/scout-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "253c8f07121d86f84e2fa0097126c93d6d361f517ff92335decf430372967166"
    end
    on_arm do
      url "https://github.com/scoutapp/scout-cli/releases/download/v#{version}/scout-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "9e87c246bac2458eeabea212907f17f5c90b096a8d5562a196b2a95a368ac1af"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/scoutapp/scout-cli/releases/download/v#{version}/scout-cli_#{version}_linux_amd64.tar.gz"
      sha256 "8c40b4ef98710d71d26223f032d2cddf9a2f4bb4627fe427d9b5edacc9e59f0d"
    end
    on_arm do
      url "https://github.com/scoutapp/scout-cli/releases/download/v#{version}/scout-cli_#{version}_linux_arm64.tar.gz"
      sha256 "921b4e693b041e297a562d3270f86d87fabba77670beaf0ce88d3fc0ee1ac2e0"
    end
  end

  # No zap stanza required
end
