# This file was generated by GoReleaser. DO NOT EDIT.
cask "scout-cli" do
  name "scout-cli"
  desc "Scout APM CLI — monitor application performance from the terminal"
  homepage "https://github.com/scoutapp/scout-cli"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scout"

  on_macos do
    on_intel do
      url "https://github.com/scoutapp/scout-cli/releases/download/v#{version}/scout-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "79905eecc9ab172c2904b704ad9b608fa65d8b84ac2d183bcb94edde9f314a5d"
    end
    on_arm do
      url "https://github.com/scoutapp/scout-cli/releases/download/v#{version}/scout-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "cc1647c8cb00491b132b4110608ece5229984b40741b9b6a75b6a1f8d54ddcc8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/scoutapp/scout-cli/releases/download/v#{version}/scout-cli_#{version}_linux_amd64.tar.gz"
      sha256 "7a9d14b31402a413361a94b4113dfcc1c5f4cff17b66ca724c9733af13057151"
    end
    on_arm do
      url "https://github.com/scoutapp/scout-cli/releases/download/v#{version}/scout-cli_#{version}_linux_arm64.tar.gz"
      sha256 "f6e5c7e1bd3a94d94612e67622eec73b80026c67aacd3f31832850d09695d5d9"
    end
  end

  # No zap stanza required
end
